apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  selector:
    matchLabels:
      app: users-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: usersapi
        image: moneletizi94/usersapi
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000


